repos:
  - repo: local
    hooks:
      - id: moon-fmt
        name: moon fmt
        entry: moon fmt
        language: system
        pass_filenames: false
      - id: moon-info
        name: moon info
        entry: moon info
        language: system
        pass_filenames: false
      - id: moon-test
        name: moon test
        entry: moon test
        language: system
        pass_filenames: false