name: check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        version: [stable]
        os:
          - name: ubuntu-latest
            triple: x86_64-linux-gnu
          - name: windows-latest
            triple: x86_64-w64-mingw32

          
      fail-fast: false
    runs-on: ${{ matrix.os.name }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Moon
        uses: illusory0x0/setup-moonbit@v0.1.0
        with: 
          version: ${{ matrix.version }}

      - name: moon version
        run: |
          moon version --all

      - name: install module dependencies
        run: |
          moon update
          moon install

      - name: moon check
        continue-on-error: true
        run: moon check --deny-warn

      - name: moon info
        run: |
          moon info --target wasm,wasm-gc,js,native
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: moon test
        run: |
          moon test --target all,native
          moon test --target all,native --release

      - name: moon test --doc
        run: |
          moon test --doc